package com.cohen.hackathonworld.Model;

public enum PROJECT_LIFE_LEVELS {
    GENERAL,
    ASSESSMENT_AND_PLANNING_LEVEL,
    SOFTWARE_REQUIREMENTS_SPECIFICATION_LEVEL,
    DESIGN_LEVEL,
    DEVELOPMENT_LEVEL,
    QUALITY_ASSURANCE_LEVEL
}
